In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
W = np.linspace(-10, 10, 5)
B = np.linspace(-15, 15, 5)

In [13]:
W

array([-10.,  -5.,   0.,   5.,  10.])

In [14]:
B

array([-15. ,  -7.5,   0. ,   7.5,  15. ])

In [16]:
w, b = np.meshgrid(W, B)
w

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [17]:
b

array([[-15. , -15. , -15. , -15. , -15. ],
       [ -7.5,  -7.5,  -7.5,  -7.5,  -7.5],
       [  0. ,   0. ,   0. ,   0. ,   0. ],
       [  7.5,   7.5,   7.5,   7.5,   7.5],
       [ 15. ,  15. ,  15. ,  15. ,  15. ]])

In [19]:
print(np.meshgrid(W, B))

[array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]]), array([[-15. , -15. , -15. , -15. , -15. ],
       [ -7.5,  -7.5,  -7.5,  -7.5,  -7.5],
       [  0. ,   0. ,   0. ,   0. ,   0. ],
       [  7.5,   7.5,   7.5,   7.5,   7.5],
       [ 15. ,  15. ,  15. ,  15. ,  15. ]])]


In [23]:
for w1,b1 in zip(w,b):
    for w2, b2 in zip(w1, b1):
        print(w2, b2)    

-10.0 -15.0
-5.0 -15.0
0.0 -15.0
5.0 -15.0
10.0 -15.0
-10.0 -7.5
-5.0 -7.5
0.0 -7.5
5.0 -7.5
10.0 -7.5
-10.0 0.0
-5.0 0.0
0.0 0.0
5.0 0.0
10.0 0.0
-10.0 7.5
-5.0 7.5
0.0 7.5
5.0 7.5
10.0 7.5
-10.0 15.0
-5.0 15.0
0.0 15.0
5.0 15.0
10.0 15.0
