In [1]:
import torch
from torch.utils.data import Dataset

In [2]:
class try_set(Dataset):
    def __init__(self, length=100, transform=None) -> None:
        super().__init__()
        
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

In [3]:
dataset = try_set()

In [4]:
dataset[0]

(tensor([2., 2.]), tensor([1.]))

Transformers

In [5]:
from typing import Any


class add_mult(object):
    def __init__(self, addx=1, muly=1) -> None:
        self.addx = addx
        self.muly = muly
    
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

Two ways to apply transforms

In [6]:
a_m = add_mult()
dataset_ = try_set(transform=a_m)

In [7]:
dataset_[0]

(tensor([3., 3.]), tensor([1.]))

Compose Transforms

In [8]:
class mult(object):
    def __init__(self, mul=1):
        self.mul = mul
    
    def __call__(self, sample):
        x = sample[0]
        y = sample [1]
        x = x * self.mul
        y = y * self.mul
        sample = x, y
        return sample

In [10]:
from torchvision import transforms
d_t = transforms.Compose([add_mult(), mult(2)])
d_t

Compose(
)

In [11]:
dataset_tr = try_set(transform=d_t)
dataset_tr[0]

(tensor([6., 6.]), tensor([2.]))